password-gen() {
    head -c 15 /dev/urandom | base64 | tr +/ -_
}

update() {
    apt update
    apt upgrade -y
    apt autopurge -y
    journalctl --vacuum-time=7d
    apt clean
}

ssl-cert-add() {
    local NAME=$1
    if grep ^$NAME$ ~/certs &> /dev/null; then
        return 1
    fi
    echo $NAME >> ~/certs
}

ssl-cert-update() {
    local NAME=$1
    local MODE
    local LIST
    case $NAME in
        sites) MODE=run
        cd /etc/apache2/sites-enabled
        LIST=$(ls -I "*ssl.conf" | sed "s/\.conf//" | paste -sd,);;
        certs) MODE=certonly
        LIST=$(paste -sd, ~/certs);;
        *) echo "Certificate does not exists"; return 1;;
    esac
    certbot $MODE -n --apache --cert-name $NAME --expand -d $LIST
}

make-site() {
    if [ -z $1 ]; then
        echo "make-site <domain> [empty]"
        return 1
    fi
    local NAME=$1
    cd /etc/apache2/sites-available
    if [ -e $NAME.conf ]; then
        echo "Site exists"
        return 1
    fi
    cp 000-default.conf $NAME.conf
    sed -i -e "s/#\(ServerName\).*/\1 $NAME/" \
    -e "s|\(DocumentRoot\).*|\1 /var/www/$NAME/public_html|" $NAME.conf
    a2ensite $NAME
    systemctl reload apache2
    if [ "$2" != empty ]; then
        cd /var/www
        mkdir $NAME
        cp -r html $NAME/public_html
        ssl-cert-update sites
    fi
}

mariadb-create-user() {
    if [ -z $1 ]; then
        echo "mariadb-create-user <name> => <password>"
        return 1
    fi
    local NAME=$1
    local PASSWORD=$(password-gen)
    mariadb -e "create database if not exists $NAME;
    create user $NAME@localhost identified by '$PASSWORD';
    grant select, insert, update, delete on $NAME.* to $NAME@localhost;
    " && echo $PASSWORD
}

mail-add-user() {
    if [ -z $1 ]; then
        echo "mail-add-user <user>@<domain> => <password>"
        return 1
    fi
    local USERNAME=${1%@*}
    local DOMAINNAME=${1#*@}
    domain-get-id() {
        mariadb -N -B -e "select id from mail.domains where domain = '$1'"
    }
    local ID=$(domain-get-id $DOMAINNAME)
    if [ -z $ID ]; then
        read -p "Enter mail server for $DOMAINNAME: " NAME
        mariadb -e "insert into mail.domains values (null, '$DOMAINNAME')"
        ID=$(domain-get-id $DOMAINNAME)
        ssl-cert-add $NAME &&
        ssl-cert-update certs &&
        systemctl reload postfix dovecot
    fi
    local PASSWORD=$(password-gen)
    echo "Password for $1: $PASSWORD"
    PASSWORD=$(doveadm pw -p $PASSWORD -s BLF-CRYPT)
    mariadb -e "insert into mail.users values
    (null, '$USERNAME', '${PASSWORD#*\}}', $ID)"
    unset -f domain-get-id
}
