password-gen() {
    head -c 15 /dev/urandom | base64 | tr +/ -_
}

update() {
    apt update
    apt upgrade -y
    apt autopurge -y
    journalctl --vacuum-time=7d
    apt clean
}

make-site() {
    if [ -z $1 ]; then
        echo "make-site <domain> [empty, proxy] <from> <to>"
        return 1
    fi
    local NAME=$1
    cd /etc/apache2/sites-available
    if [ -e $NAME.conf ]; then
        echo "Site exists"
        return 1
    fi
    cp 000-default.conf $NAME.conf
    sed -i "s/<domain_name>/$NAME/" $NAME.conf
    cp default-ssl.conf $NAME-ssl.conf
    if [ "$2" = proxy ]; then
        sed -i "s|DocumentRoot.*|ProxyPreserveHost On\n    ProxyPass $3 $4\n    ProxyPassReverse $3 $4|" $NAME-ssl.conf
    fi
    sed -i "s/<domain_name>/$NAME/" $NAME-ssl.conf
    a2ensite $NAME.conf $NAME-ssl.conf > /dev/null
    systemctl reload apache2
    if [ -z $2 ]; then
        cd /var/www
        mkdir $NAME
        cp -r html $NAME/public_html
    fi
}

mariadb-create-user() {
    if [ -z $1 ]; then
        echo "mariadb-create-user <name> [all] => <password>"
        return 1
    fi
    local NAME=$1
    local PASSWORD=$(password-gen)
    local PRIVILEGES
    if [ -z $2 ]; then
        PRIVILEGES="select, insert, update, delete"
    elif [ $2 = all ]; then
        PRIVILEGES="all privileges"
    else
        echo "Wrong usage"
        return 1
    fi
    mariadb -e "create database if not exists $NAME;
    create user $NAME@localhost identified by '$PASSWORD';
    grant $PRIVILEGES on $NAME.* to $NAME@localhost;"
    echo "$NAME: $PASSWORD" >> ~/local/mariadb.users
    echo $PASSWORD
}

mail-create-user() {
    if [ -z $1 ]; then
        echo "mail-create-user <user>@<domain> => <password>"
        return 1
    fi
    local USERNAME=${1%@*}
    local DOMAINNAME=${1#*@}
    domain-get-id() {
        mariadb -N -B -e "select id from mail.domains where domain = '$1'"
    }
    local ID=$(domain-get-id $DOMAINNAME)
    if [ -z $ID ]; then
        mariadb -e "insert into mail.domains values (null, '$DOMAINNAME')"
        ID=$(domain-get-id $DOMAINNAME)
    fi
    local PASSWORD=$(password-gen)
    echo "Password for $1: $PASSWORD"
    PASSWORD=$(doveadm pw -p $PASSWORD -s BLF-CRYPT)
    mariadb -e "insert into mail.users values (null, '$USERNAME', '${PASSWORD#*\}}', $ID)"
    unset -f domain-get-id
}
