password-gen() {
    head -c 15 /dev/urandom | base64 | tr +/ -_
}

update() {
    apt update
    apt upgrade -y
    apt autopurge -y
    journalctl --vacuum-time=7d
    apt clean
}

make-site() {
    local NAME=$1
    cd /etc/apache2/sites-available
    if [ -z $NAME -o -e $NAME.conf ]; then
        echo "Site exists"
        return 1
    fi
    cp 000-default.conf $NAME.conf
    sed -i -e "s/#\(ServerName\).*/\1 $NAME/" \
    -e "s|\(DocumentRoot\).*|\1 /var/www/$NAME/public_html|" $NAME.conf
    a2ensite $NAME
    if [ "$2" != empty ]; then
        cd /var/www
        mkdir $NAME
        cp -r html $NAME/public_html
    fi
    ssl-cert-add $NAME
}

ssl-cert-add() {
    local NAME=$1
    cd /etc/apache2
    if [ -z $NAME ] || grep ^$NAME$ certs >> /dev/null; then
        echo "Domain exists"
        return 1
    fi
    printf \\n$NAME >> certs
}

ssl-cert-update() {
    certbot $1 --apache --expand -d $(cat /etc/apache2/certs | tr \\n ,)
}

mariadb-create-user() {
    local NAME=$1
    local PASSWORD=$(password-gen)
    echo "$PASSWORD"
    mariadb -e "create database if not exists $NAME;
    create user $NAME@localhost identified by '$PASSWORD';
    grant select, insert, update, delete on $NAME.* to $NAME@localhost;"
}

mail-add-domain() {
    mariadb -e "insert into mail.domains values (null, '$1')"
}

mail-add-user() {
    USERNAME=${1%@*}
    DOMAINNAME=${1#*@}
    PASSWORD=$(password-gen)
    echo $PASSWORD
    PASSWORD=$(doveadm pw -p $PASSWORD -s BLF-CRYPT)
    mariadb -e "insert into mail.users values (null, '$USERNAME', '${PASSWORD#*\}}', (select id from mail.domains where domain = '$DOMAINNAME'))"
}
