#!/usr/bin/env bash
START_PATH=$PWD
read -p "Введите домен: " DOMAIN
echo "DOMAIN=$DOMAIN" >> ~/.bashrc
cat bashrc >> ~/.bashrc
source bashrc
rm bashrc
apt update && apt upgrade -y
apt install -y php php-fpm apache2 certbot python3-certbot-apache mariadb-server php-mysql mariadb-client postfix dovecot-imapd speedtest-cli

cd /etc/ssh
sed -i "s/#PasswordAuthentication yes/PasswordAuthentication no/" sshd_config
sed -i "s/#Port 22/Port 17779/" sshd_config
rm -f sshd_config.d/*
systemctl restart sshd

PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
a2dismod php$PHP_VERSION mpm_prefork
a2enmod mpm_event proxy_fcgi http2
a2enconf php$PHP_VERSION-fpm
a2dissite 000-default.conf

cd /etc/apache2
sed -i "s/Indexes FollowSymLinks/-Indexes/" apache2.conf
cd sites-available
cp 000-default.conf $DOMAIN.conf
sed -i "s/#ServerName www.example.com/ServerName $DOMAIN/" $DOMAIN.conf
sed -i "s|DocumentRoot /var/www/html|Redirect permanent / http://www.$DOMAIN|" $DOMAIN.conf
a2ensite $DOMAIN
systemctl restart apache2

certbot register --agree-tos --no-eff-email -m postmaster@$DOMAIN
certbot --apache -d $DOMAIN
make-site www
make-site mail
mariadb-secure-installation

cd /etc/postfix
sed -i "s|^smtpd_tls_cert_file=.*$|smtpd_tls_cert_file=/etc/letsencrypt/live/$DOMAIN/fullchain.pem|" main.cf
sed -i "s|^smtpd_tls_key_file=.*$|smtpd_tls_key_file=/etc/letsencrypt/live/$DOMAIN/privkey.pem|" main.cf
echo "smtpd_use_tls = yes
local_recipient_maps = hash:/etc/postfix/valid_recipients
home_mailbox = Maildir/" >> main.cf
read -s -p "Пароль для postmaster: " PASSWORD
echo
mailuseradd postmaster $PASSWORD
sed -i "/^postmaster:/d" /etc/aliases
newaliases
systemctl restart postfix

cd /etc/dovecot/conf.d
sed -i "s/^#auth_username_format = .*$/auth_username_format = %n/" 10-auth.conf
sed -i "s|^mail_location = .*$|mail_location = maildir:~/Maildir|" 10-mail.conf
sed -i "s|^ssl_cert = .*$|ssl_cert = </etc/letsencrypt/live/$DOMAIN/fullchain.pem|" 10-ssl.conf
sed -i "s|^ssl_key = .*$|ssl_key = </etc/letsencrypt/live/$DOMAIN/privkey.pem|" 10-ssl.conf
systemctl restart dovecot

speedtest-cli
cd $START_PATH
rm $0
