#!/usr/bin/env bash
START_PATH=$PWD
read -p "Введите домен: " DOMAIN
echo "DOMAIN=$DOMAIN" >> ~/.bashrc
cat bashrc >> ~/.bashrc
source bashrc
rm bashrc
apt update && apt upgrade -y

apt install speedtest-cli
speedtest-cli
cd $START_PATH
rm $0
