update() {
    apt update
    apt upgrade -y
    apt autopurge -y
    journalctl --vacuum-time=7d
    apt clean
}

make-site() {
    local name=$1.$DOMAIN
    cd /var/www
    if [ -e "$name" -o -z "$1" ]; then
        echo "Сайт уже существует"
        return 1
    fi
    mkdir $name
    cp -r html $name/public_html
    cd /etc/apache2/sites-available
    cp 000-default.conf $name.conf
    sed -i "s/#ServerName www.example.com/ServerName $name/" $name.conf
    sed -i "s|DocumentRoot /var/www/html|DocumentRoot /var/www/$name/public_html|" $name.conf
    a2ensite $name
    systemctl reload apache2
    certbot --apache --expand -d $(ls /var/www | grep $DOMAIN | tr "\n" ",")$DOMAIN
}

mariadb-create-user() {
    local name="$1"
    local password="$2"
    local privileges
    case $3 in
        "crud")
        privileges="select, insert, update, delete"
        ;;
        "def")
        privileges="select, insert, update, delete, create, drop, index, alter"
        ;;
        *)
        echo "usage: mariadb-create-user <name> <password> <privileges>"
        echo "privileges list: crud, def"
        return 1
        ;;
    esac
    mariadb -e 'drop database if exists `'"$name"'`;'
    mariadb -e 'create database `'"$name"'`;'
    mariadb -e 'drop user if exists `'"$name"'`@localhost;'
    mariadb -e 'create user `'"$name"'`@localhost identified by '\'"$password"\'';'
    mariadb -e 'grant '"$privileges"' on `'"$name"'`.* to `'"$name"'`@localhost;'
    echo "$name: '$password'" >> ~/mariadb.user
}

mailuseradd() {
    (set -e
    USERNAME=$1
    PASSWORD=$2
    if [ -z "$USERNAME" -o -z "$PASSWORD" ]; then
        echo "Пустой аргумент"
        false
    fi
    if id "$USERNAME" &> /dev/null; then
        echo "Пользователь существует"
        false
    fi
    useradd -m -s /usr/sbin/nologin "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    cd /etc/postfix
    echo "$USERNAME@$DOMAIN OK" >> valid_recipients
    postmap valid_recipients)
}

mailuserdel() {
    (set -e
    USERNAME=$1
    if [ -z "$USERNAME" ]; then
        echo "Пустой аргумент"
        false
    fi
    cd /etc/postfix
    if ! grep -q "^$USERNAME@$DOMAIN" valid_recipients; then
        echo "Пользователя не существует"
        false
    fi
    userdel -r "$USERNAME"
    sed -i "/^$USERNAME@$DOMAIN/d" valid_recipients
    postmap valid_recipients)
}
